<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 c:\Users\Sirat\Downloads\arch_linux_logo.glb -t --suspense
Author: xtm (https://sketchfab.com/xtm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arch-linux-logo-8fbac89ca2d64696a87850e80f423f27
Title: Arch Linux Logo
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Object_2: THREE.Mesh;
		};
		materials: {
			['Material.001']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>('/models/arch_linux_logo.glb'));
</script>

{/* @ts-ignore */ null}
<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Object_2.geometry}
			material={gltf.materials['Material.001']}
			rotation={[-Math.PI / 2, 0, 0]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{/* @ts-ignore */ null}

	{@render children?.({ ref })}
</T.Group>
